services:
  web.mhc:
    build:
      context: .
      dockerfile: ./gpu.Dockerfile 
    env_file:
      - ./.env
    command: python main.py
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - .:/usr/app
    ports:
      - 80:8000
      - 443:8000

networks:
  default:
    name: mhc